filebeat.inputs:
- type: log
  paths:
    - /var/log/execve.log
  fields:
    log_type: execve_command_execution

- type: log
  paths:
    - /var/log/audit/audit.log
  fields:
    log_type: auditd_command_execution

output.logstash:
  hosts: ["your-logstash-ip:5055"]