version: '3.8'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.3
    container_name: logstash-command-log
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5055:5055"
    networks:
      - elk_default

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.14.3
    container_name: filebeat-command-log
    user: root
    volumes:
      - /var/log/execve.log:/var/log/execve.log
      - /var/log/audit/audit.log:/var/log/audit/audit.log
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - logstash

networks:
  elk_default:
    external: true